"""
Influence field generated by hand positions.

Creates spatial force zones around each detected hand with configurable
radius, strength, and falloff. Forces from multiple hands stack additively,
enabling natural multi-hand interaction.

V2 design:
- Attraction toward hand center (gravity-like)
- Wake push along hand movement direction
- Inverse-square or Gaussian falloff
- Per-hand speed affects force magnitude
- Supports future multi-person expansion
"""

import math

from ..config import Config


class InfluenceField:
    """Spatial influence field driven by hand positions.

    Each hand creates an influence zone. Particles within range experience:
    1. Attraction toward the hand (falls off with distance)
    2. Wake force along hand movement direction (proportional to speed)

    Forces from multiple hands stack additively.

    Public interface:
        update(hands)      — set current hand states
        get_force(px, py)  — force vector at a particle position
        toggle()           — enable/disable
    """

    def __init__(
        self,
        radius: float = Config.INFLUENCE_RADIUS,
        strength: float = Config.INFLUENCE_STRENGTH,
        min_distance: float = Config.INFLUENCE_MIN_DISTANCE,
        falloff: str = Config.INFLUENCE_FALLOFF,
        gaussian_sigma: float = Config.INFLUENCE_GAUSSIAN_SIGMA,
        wake_strength: float = Config.INFLUENCE_WAKE_STRENGTH,
        enabled: bool = Config.INFLUENCE_ENABLED,
    ) -> None:
        """Initialize the influence field.

        Args:
            radius: Maximum influence radius in pixels.
            strength: Base attraction strength.
            min_distance: Minimum distance to avoid force singularity.
            falloff: "inverse_square" or "gaussian".
            gaussian_sigma: Sigma for gaussian falloff.
            wake_strength: Multiplier for hand-movement push force.
            enabled: Whether the field is active.
        """
        self.radius = radius
        self.strength = strength
        self.min_distance = min_distance
        self.falloff = falloff
        self.gaussian_sigma = gaussian_sigma
        self.wake_strength = wake_strength
        self.enabled = enabled

        # Internal hand states: list of (x, y, speed, dx, dy)
        self._hands: list[tuple[float, float, float, float, float]] = []

    def update(
        self,
        hands: list[tuple[float, float, float, float, float]],
    ) -> None:
        """Update the field with current hand positions and movement.

        Args:
            hands: List of (px, py, speed, dx, dy) tuples for each hand.
                px, py: Hand position in pixels.
                speed: Smoothed hand movement speed.
                dx, dy: Hand velocity direction (frame delta).
        """
        self._hands = hands

    def get_force(self, px: float, py: float) -> tuple[float, float]:
        """Compute total influence force at a particle position.

        Sums contributions from all active hands with distance falloff.

        Args:
            px: Particle x position in pixels.
            py: Particle y position in pixels.

        Returns:
            (fx, fy) total force vector, or (0.0, 0.0) if disabled.
        """
        if not self.enabled or not self._hands:
            return (0.0, 0.0)

        total_fx = 0.0
        total_fy = 0.0

        for hx, hy, speed, hdx, hdy in self._hands:
            dx = hx - px
            dy = hy - py
            dist = math.sqrt(dx * dx + dy * dy)

            if dist >= self.radius or dist < 0.001:
                continue

            # Normalized direction toward hand
            ndx = dx / dist
            ndy = dy / dist

            # ---- Attraction force ----
            attraction = self._compute_falloff(dist)

            total_fx += ndx * attraction
            total_fy += ndy * attraction

            # ---- Wake force (along hand movement direction) ----
            # Stronger when hand moves faster and particle is closer
            wake_factor = (
                speed
                * self.wake_strength
                * (1.0 - dist / self.radius)
            )
            total_fx += hdx * wake_factor
            total_fy += hdy * wake_factor

        return (total_fx, total_fy)

    def _compute_falloff(self, dist: float) -> float:
        """Compute force magnitude for a given distance.

        Args:
            dist: Distance from hand center (already clamped to [min_dist, radius]).

        Returns:
            Force magnitude at this distance.
        """
        d = max(dist, self.min_distance)

        if self.falloff == "gaussian":
            # Gaussian: strength * exp(-d² / (2σ²))
            sigma2 = 2.0 * self.gaussian_sigma * self.gaussian_sigma
            return self.strength * math.exp(-(d * d) / sigma2)
        else:
            # Inverse-square (default): strength / d²
            return self.strength / (d * d)

    def get_influence_at(self, px: float, py: float) -> float:
        """Get the raw influence magnitude (0.0–1.0) at a position.

        Useful for color blending, size modulation, etc.

        Args:
            px: Position x in pixels.
            py: Position y in pixels.

        Returns:
            Influence factor from 0.0 (no influence) to 1.0 (max).
        """
        if not self._hands:
            return 0.0

        max_factor = 0.0
        for hx, hy, speed, hdx, hdy in self._hands:
            dx = hx - px
            dy = hy - py
            dist = math.sqrt(dx * dx + dy * dy)
            if dist < self.radius:
                factor = 1.0 - (dist / self.radius)
                # Quadratic falloff for a more natural feel
                factor = factor * factor
                # Boost by hand speed
                factor *= (1.0 + speed * 5.0)
                factor = min(1.0, factor)
                max_factor = max(max_factor, factor)
        return max_factor

    def has_active_hands(self) -> bool:
        """Check if any hands are currently influencing the field."""
        return len(self._hands) > 0
